### ISSUE TITLE
audio viz behaves strangely upon scroll

### ISSUE THREAD

**Issue by esaule** [BridgesUNCC/bridgesAPI#48]
When looking at an audio assignment on the clone server, it behave strangely upon scrolling.
It resets the playing of the clip if I scroll.It probably should not be doing that.
Assigning @quaiquai  and @LightBoat9  becasue I am not sure who is the right person to look at it.

**Comment by esaule** [comment]
As far as I know the correct JS file is https://github.com/BridgesUNCC/bridgesAPI/blob/master/public/js/audio/audio.js

**Comment by AlecGoncharow** [comment]
Do you have a link to an uploaded audioclip assignment?

**Comment by esaule** [comment]
http://bridges-cs.herokuapp.com/assignments/133/esaule

**Comment by krs-world** [comment]
Do you mean, if I set the pointer to some place in the audio wave, it still plays the whole thing? Which is strange.. I would have expected it to play just that part between the two sliders each time you hit the play button.

**Comment by AlecGoncharow** [comment]
If it's worth anything, I don't have that issue on my end, I am able to pan around the clip fine without the audio clip resetting.

I am running Firefox 79.0

**Comment by esaule** [comment]
Alright, what I do is hit play.
While the music is playing, scroll up or down.
Doing that reset the music to the beginning.

Looking more carefully it seems that even if the music is not playing, scrolling "resets" the subassignment view because I see the waveform "blink".

So I am guessing that the music restarting from the beginning is an artifact of the of the subassignment resetting.

**Comment by esaule** [comment]
I am running firefox 75 on this machine (debian stable)

**Comment by esaule** [comment]
BTW, I also get a bunch of warning in the console:

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. esaule
Object { map_overlay: false, coord_system_type: "cartesian", encoding: "RAW", numChannels: 2, sampleRate: 44100, bitsPerSample: 16, numSamples: 449519, samples: "CgAAACAAAQA0AAcASAAQAGAAHQB+AC8ApABHANIAZgD6AIIAFwGXAB8BnQANAZQA4AB2AJcARAAoAPT/kf+D/8r+6/7R/Sz+5vx4/SL85vyg+4r8aPtt/EP7Zvwa+2b87Pps/Lv6d/zO+rH8Rfss/Sz85f2H/dn+BP/T/38AvwCaAXABKwLSAToC8gHMAdYBPQGxAbIAmQFQAJ0BIgDEAQwA8wECACEC9P9AAtz/TQLi/3oCEwDbAngAhQMRAYAEhwFeBa8B6QVWAeUFaAA4BSb/FQS3/ZwCjvw6Adv7HwCa+3P/yPtL/zP8ef/I/Ov/lf2BAJv+JwHb/+cBUAG/As4CoANCBIMEXwUiBQAGWwUSBiAFjQVpBIwERAMlA78BYQHI/0P/U/0K/bH60PoF+Kj4hvWg9lfzoPRU8ZryZ+/j8Mvtp++g7DPvNeyz77bs0/DG7VzyK+/B81fwuvT88Cv1LvET9QTxt/Ta8ET05vAP9FDxOPQg8sz0S/PF9cT08PZb9jv4/PeA+XX5rPqq+rv7qvuj/H78i/1v/Yv+p/6o/zIA6QAbAigCKgRaA0sGkARUCMQFIQrfBnELywcbDGsIHgy/CIsL9AjFCioJDQqDCaQJAwqkCY8K/gkWC6kKiwt8C+YLXQzfC9sMVAu0DEUK3gu/CF0KZQfnCJ4G7QfMBuEHHwgBCTUK4ArFDCcNMg8tDx8RjhBpEjERBRMfEUMTuRBWEz8QdBP8D70TGhAYFJIQYxRYETkU+BFiEywSzRG8EacPdxB8DdIOqwsfDYAKvQv0CfMKswmHCm8JNArRCKEJzQeHCGgG0QbJBJUEDAPdASYB0f5T/7L7hf2w+NX7HPZW+hT02viL8nD3ZPEh9oHwAPXR7zz0We/Q8x/vhPP47irzyO7D8pbudPJY7pPyS+5c85XuqfQO7yP2yu9196zwSfil8Wj4pvLb94rzi/YV9LX0BfS18nfzxPCJ8m7vyfHr7qvxc+918izx…" }
audio.js:532:13
WebGL warning: drawArraysInstanced: Drawing without vertex attrib 0 array enabled forces the browser to do expensive emulation work when running on desktop OpenGL platforms, for example on Mac. It is preferable to always draw with vertex attrib 0 array enabled, by using bindAttribLocation to bind some always-used attribute to location 0. audio.js:283:16
WebGL warning: drawArraysInstanced: Drawing without vertex attrib 0 array enabled forces the browser to do expensive emulation work when running on desktop OpenGL platforms, for example on Mac. It is preferable to always draw with vertex attrib 0 array enabled, by using bindAttribLocation to bind some always-used attribute to location 0. audio.js:317:24
Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted. esaule
Object { map_overlay: false, coord_system_type: "cartesian", encoding: "RAW", numChannels: 2, sampleRate: 44100, bitsPerSample: 16, numSamples: 449519, samples: "CgAAACAAAQA0AAcASAAQAGAAHQB+AC8ApABHANIAZgD6AIIAFwGXAB8BnQANAZQA4AB2AJcARAAoAPT/kf+D/8r+6/7R/Sz+5vx4/SL85vyg+4r8aPtt/EP7Zvwa+2b87Pps/Lv6d/zO+rH8Rfss/Sz85f2H/dn+BP/T/38AvwCaAXABKwLSAToC8gHMAdYBPQGxAbIAmQFQAJ0BIgDEAQwA8wECACEC9P9AAtz/TQLi/3oCEwDbAngAhQMRAYAEhwFeBa8B6QVWAeUFaAA4BSb/FQS3/ZwCjvw6Adv7HwCa+3P/yPtL/zP8ef/I/Ov/lf2BAJv+JwHb/+cBUAG/As4CoANCBIMEXwUiBQAGWwUSBiAFjQVpBIwERAMlA78BYQHI/0P/U/0K/bH60PoF+Kj4hvWg9lfzoPRU8ZryZ+/j8Mvtp++g7DPvNeyz77bs0/DG7VzyK+/B81fwuvT88Cv1LvET9QTxt/Ta8ET05vAP9FDxOPQg8sz0S/PF9cT08PZb9jv4/PeA+XX5rPqq+rv7qvuj/H78i/1v/Yv+p/6o/zIA6QAbAigCKgRaA0sGkARUCMQFIQrfBnELywcbDGsIHgy/CIsL9AjFCioJDQqDCaQJAwqkCY8K/gkWC6kKiwt8C+YLXQzfC9sMVAu0DEUK3gu/CF0KZQfnCJ4G7QfMBuEHHwgBCTUK4ArFDCcNMg8tDx8RjhBpEjERBRMfEUMTuRBWEz8QdBP8D70TGhAYFJIQYxRYETkU+BFiEywSzRG8EacPdxB8DdIOqwsfDYAKvQv0CfMKswmHCm8JNArRCKEJzQeHCGgG0QbJBJUEDAPdASYB0f5T/7L7hf2w+NX7HPZW+hT02viL8nD3ZPEh9oHwAPXR7zz0We/Q8x/vhPP47irzyO7D8pbudPJY7pPyS+5c85XuqfQO7yP2yu9196zwSfil8Wj4pvLb94rzi/YV9LX0BfS18nfzxPCJ8m7vyfHr7qvxc+918izx…" }
audio.js:532:13
WebGL warning: drawArraysInstanced: Vertex attrib array 1 is enabled but has no buffer bound. audio.js:283:16
WebGL warning: drawArraysInstanced: Drawing without vertex attrib 0 array enabled forces the browser to do expensive emulation work when running on desktop OpenGL platforms, for example on Mac. It is preferable to always draw with vertex attrib 0 array enabled, by using bindAttribLocation to bind some always-used attribute to location 0. audio.js:317:24
WebGL warning: drawArraysInstanced: Vertex attrib array 2 is enabled but has no buffer bound. audio.js:258:11
WebGL warning: drawArraysInstanced: Vertex attrib array 1 is enabled but has no buffer bound. audio.js:283:16
WebGL warning: drawArraysInstanced: Vertex attrib array 2 is enabled but has no buffer bound. audio.js:258:11
WebGL warning: drawArraysInstanced: Vertex attrib array 1 is enabled but has no buffer bound. audio.js:283:16
WebGL warning: drawArraysInstanced: Vertex attrib array 2 is enabled but has no buffer bound. audio.js:258:11
WebGL warning: drawArraysInstanced: Vertex attrib array 1 is enabled but has no buffer bound. audio.js:283:16
WebGL warning: drawArraysInstanced: Vertex attrib array 2 is enabled but has no buffer bound. audio.js:258:11
WebGL warning: drawArraysInstanced: Vertex attrib array 1 is enabled but has no buffer bound. audio.js:283:16
WebGL warning: drawArraysInstanced: Vertex attrib array 2 is enabled but has no buffer bound. audio.js:258:11
WebGL warning: drawArraysInstanced: Vertex attrib array 1 is enabled but has no buffer bound. audio.js:283:16
WebGL warning: drawArraysInstanced: Vertex attrib array 2 is enabled but has no buffer bound. audio.js:258:11
WebGL warning: drawArraysInstanced: Vertex attrib array 1 is enabled but has no buffer bound. audio.js:283:16
WebGL warning: drawArraysInstanced: Vertex attrib array 2 is enabled but has no buffer bound. audio.js:258:11
WebGL warning: drawArraysInstanced: Vertex attrib array 1 is enabled but has no buffer bound. audio.js:283:16
WebGL warning: drawArraysInstanced: Vertex attrib array 2 is enabled but has no buffer bound. audio.js:258:11
WebGL warning: drawArraysInstanced: Vertex attrib array 1 is enabled but has no buffer bound. audio.js:283:16
WebGL warning: drawArraysInstanced: Drawing without vertex attrib 0 array enabled forces the browser to do expensive emulation work when running on desktop OpenGL platforms, for example on Mac. It is preferable to always draw with vertex attrib 0 array enabled, by using bindAttribLocation to bind some always-used attribute to location 0. audio.js:283:16
Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted.

**Comment by krs-world** [comment]
Sounds like scrolling is trying to redraw t he page and in the process, the play sequence is started. If that is the case, we might need to catch these events and respond accordingly.

	— krs

_________________________________________________________________________________
  
K.R.Subramanian                                     Phone: (704) 687-8579
Assoc. Professor, Computer Science          FAX:   (704) 687-3516
UNC Charlotte, Woodward 435E                Email: krs@uncc.edu
Charlotte, NC 28223-0001                        www.cs.uncc.edu/~krs
-----------------------------------------------------------
If you are not the intended recipient of this transmission or a person responsible for delivering it to the intended recipient, any disclosure, copying, distribution, or other use of any of the information in this transmission is strictly prohibited. If you have received this transmission in error, please notify me immediately. Thank you.

**Comment by esaule** [comment]
I suppose an important question is can anyone reproduce it besides me?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by esaule** [comment]
this is happening on more than just audio. This is also happening on maps.
Open a map assignment such as http://bridges-cs.herokuapp.com/assignments/109/bridges_testing

zoom and pan the visualization, then scroll the whole page. You will see the map visualization reset.

**Comment by esaule** [comment]
I think this is all happening inside of multiVisconfig.js. It defines onscroll line 208 which calls update vis.
updatevis puts a 250ms timer to call visualizeassignment (what is this delay for anyway?, I feel like that is not what we want, probably it is to wait on the ajax to resolve.)

visualizeassignment seems to remove a bunch of things and add assignments again.. Since it is calling d3.audio_webgl, that function resets the time index to 0.

The real issue is that it probably should not be calling it at all if it is already visible?

**Comment by esaule** [comment]
(sorry for spammiong, I post here when I discover a new piece of information.)

There is a test in the scroll listener to check whether the assignment is already loaded so it does not load it again. I suppose that function is broken. it is function unloaded(i) line 218 of multiVisconfig.js

**Comment by esaule** [comment]
defining unloaded in the console shows a different behavior on webglmap and on a link list
unload(0) on a map returns true
while unloaded(0) on a link list returns false

I suppose the test is broken. I'll keep looking into it.

**Comment by esaule** [comment]
If I define unloaded in the console this way:

function unloaded(i) {
  // console.log(i, d3.select("#svg"+i).node());
  return (d3.select("#svg"+i).node() == null) && (d3.select("#canvas"+i).node() === null && d3.select("#vis"+i).select(".highcharts-container").empty()) && (d3.select("#canvas_webgl"+i).node() == null);
}

then unloaded(0) is false for both maps and link list.

**Comment by esaule** [comment]
I pushed a commit on bridgeAPi and deployed to clone that appears to fix the issue.

**Comment by esaule** [comment]
I deployed on live, it seems to work. Closing this bug report. But let's keep our eyes open.
