### ISSUE TITLE
tree assignment behaves strangely if paired with a shape collection

### ISSUE THREAD

**Issue by esaule** [BridgesUNCC/bridgesAPI#49]
If thereis a hape collection as first subassignment and a tree as second assignment, the styling of the edges of the tree is screwed up. I am not sure who can look into that and understand what is going on, so I am assigning everyone who worked on that web API before.

**Comment by esaule** [comment]
Even if you can't have a fix, if we can have an idea of what the problem is that would already be helpful.

**Comment by AlecGoncharow** [comment]
I'm going to assume it has something to do with the stroke attributes in
the shape collection not being isolated to the shape collection's
subassignment in the json or the way the JavaScript parses assignments

**Comment by esaule** [comment]
It is a good idea @AlecGoncharow gave today to try to reproduce the bug with other datastructure

**Comment by AlecGoncharow** [comment]
If the first assignment is not a SymbolCollection then the trees render fine. This seems to imply the rendering javascript is not parsing the assignment JSON properly. This does not affect linked lists it seems.

**Comment by esaule** [comment]
This is fixed on clone now.

What was happening is that the BST visualization was not defining a fill parameter for the edges of the BST. Because of that the rendering in libsvg of the browser was not setting the fill. And therefore was using whatever the previous fill of any svg component was.

If there was an symbol collection, it was likely that there was some kind of a fill used somewhere that changed the practical behavior of undefined fill.

The latest commit defines a proper fill for the edges. I'll deploy on live soon.
