### ISSUE TITLE
Shape Collection not being rendered right..

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/bridgesAPI#53]
I tried rendering a rectangle of 400x400 and it looks like the view is getting clipped in the visualization. There was a hard limit (probably some old code) in the client, which I had to remove to try. 

Upto 200x200 it renders correctly, after that it gets clipped. We should be able to support arbitrary sized collection of shapes specified by the user.  

Erik, you were the last to work on this on the server side.. do you recall any of this?

**Comment by krs-world** [comment]
I am trying to use the shape collection for the kd tree image compression assignment, so the shapes are in that image space (my image was 450x620. Thats the context

**Comment by krs-world** [comment]
Matthew: 

Look at the way the shape collection coordinate system is configured on the Server (d3). I think its a bit insane. Ideally, the user should be able to make shapes in any coordinate system (world coordinates) - the client is already computing the bounding box and this should be used as a basis on the server. Right now, it assumes its centered around 0, 0. We just need to do a simple window to viewport transform  (viewport is whatever we want to use for the svg shapes). So if I start with a (0, 0) to (450, 620), then that should be mapped to the device (preferably 0, 0 on the lower left, which is normal).  In other words, you might need to do a flip in the end to suit Svg's coordinates (as we do in the typical graphics pipeline).

**Comment by krs-world** [comment]
The clipping of the display is perhaps  a different or related issue.

**Comment by esaule** [comment]
are you using the clone server? the live server is running some old code.

On May 12, 2020 11:29:27 AM EDT, Kalpathi Subramanian <notifications@github.com> wrote:
>The clipping of the display is perhaps  a different or related issue.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/BridgesUNCC/bridgesAPI/issues/53#issuecomment-627417816

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by krs-world** [comment]
Tried it on clone with the same result.. here is a rectangle 620x620 with some lines in it. The top and bottom edges are missing.

_________________________________________________________________________________
  
K.R.Subramanian                                     Phone: (704) 687-8579
Assoc. Professor, Computer Science          FAX:   (704) 687-3516
UNC Charlotte, Woodward 435E                Email: krs@uncc.edu
Charlotte, NC 28223-0001                        www.cs.uncc.edu/~krs
-----------------------------------------------------------
If you are not the intended recipient of this transmission or a person responsible for delivering it to the intended recipient, any disclosure, copying, distribution, or other use of any of the information in this transmission is strictly prohibited. If you have received this transmission in error, please notify me immediately. Thank you.

**Comment by esaule** [comment]
can you post a basic driver code.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by krs-world** [comment]
Ok, I have fixed the issues with shape rendering. There were bugs in Rectangle class in comput ing bounding boxes (C++ client code) that had something to do with this, but I got a handle on hte server side and cleaned up the transformation code (for now the old code is commented out)  and put detailed comments. The Rectangle class is now specified with its lower left corner and height and width.  This is then taken care of on the server side on what it requires.

Good for someone to do some more testing and then close this issue.  Tested on local server, of course, as I dont know how to do that with clone yet.

I will need to update the Java and Python client code.. and then do the testing.

       -- krs

**Comment by esaule** [comment]
yeah, specifying rectangles by their center is kind of strange. good change!

On May 13, 2020 8:45:32 PM EDT, Kalpathi Subramanian <notifications@github.com> wrote:
>Ok, I have fixed the issues with shape rendering. There were bugs in
>Rectangle class in comput ing bounding boxes (C++ client code) that had
>something to do with this, but I got a handle on hte server side and
>cleaned up the transformation code (for now the old code is commented
>out)  and put detailed comments. The Rectangle class is now specified
>with its lower left corner and height and width.  This is then taken
>care of on the server side on what it requires.
>
>Good for someone to do some more testing and then close this issue. 
>Tested on local server, of course, as I dont know how to do that with
>clone yet.
>
>I will need to update the Java and Python client code.. and then do the
>testing.
>
>       -- krs
>
>
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/BridgesUNCC/bridgesAPI/issues/53#issuecomment-628320225

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by krs-world** [comment]
Fixed the rectangle class in both python and java and tested it. Seems to be working ok.. Regardless of the shape. you provide (assuming legal params), the visualization should be propertly centered. Else post  a comment with enough information.

**Comment by krs-world** [comment]
This has been fixed. Closing..
