### ISSUE TITLE
Audio visualization does not seem to render correctly 8-bit wave forms

### ISSUE THREAD

**Issue by esaule** [BridgesUNCC/bridgesAPI#56]
I generated a simple clip using freqPlayer in 8-bit. The sound that plays seems correct, but the wave form visualization seems broken.

http://bridges-cs.herokuapp.com/assignments/4583/esaule

I don't know enough webGL and JS to debug the issue. Maybe @krs-world , @quaiquai , or @AlecGoncharow knows how to debug it?

**Comment by esaule** [comment]
Here is an encoding of the same clip but in 16 bits http://bridges-cs.herokuapp.com/assignments/4584/esaule
They sound about the same (despite the 8-bit one is definitely a 8 bit sound). But the wave form is quite different. The 16-bit waveform is consistent with exceptation, while the 8-bit one is not.

**Comment by krs-world** [comment]
Assume you are using Java version? Yeah, I dont see the wave visualization at all.

I am still fighting with the C++ version.. the conversion of the audio data to little-endian combined with the sign of teh values is causing  incorrect  values for the audio data..

	— krs

_________________________________________________________________________________
  
K.R.Subramanian                                     Phone: (704) 687-8579
Assoc. Professor, Computer Science          FAX:   (704) 687-3516
UNC Charlotte, Woodward 435E                Email: krs@uncc.edu
Charlotte, NC 28223-0001                        www.cs.uncc.edu/~krs
-----------------------------------------------------------
If you are not the intended recipient of this transmission or a person responsible for delivering it to the intended recipient, any disclosure, copying, distribution, or other use of any of the information in this transmission is strictly prohibited. If you have received this transmission in error, please notify me immediately. Thank you.

**Comment by esaule** [comment]
I am using the C++ API actually.

I am synthesizing the wave form from sine functions, so I don't need
the reader. I pushed tiny changes to AudioClip BTW to throw exception
when values are out of bound.

**Comment by esaule** [comment]
I just fixed the issue. It is fixed in master, not propagated to heroku yet.

It was a webclient problem.
The audio.js code reconstruct a wav file from the data in bridges. Bridges represent all PCM data signed, but Wav specifies 8-bit as unsigned. So there was a need to convert in webclient javascript.
