### ISSUE TITLE
Node sizes in BRIDGES

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/bridgesAPI#71]
We seem to have  size range from 1-50 or so. I would like a much larger range. I am trying to show a graph with nodes of decreasing size away from the center and this range is just not enough. There is very little difference when you try to go through this range.

Can we increase the range and update the server - lets try it on the clone first and I will check it out. I could use t his form my current and future projects in BRIDGES.

**Comment by krs-world** [comment]
Similarly link thickness has a range of 1 to 10.0. Again it would be good to have a larger range.

**Comment by quaiquai** [comment]
done
