### ISSUE TITLE
Bridges Login..

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/bridgesAPI#73]
The BRIDGES login code might have an issue. It looks like (I tested it) it wont take a user name that is the full email address of a user. It takes just the user name (without the @school.edu part). The error message is also quite misleading and reports on the size of the user ide (20 characters -- is that a restriction ? I was able to create an account with 35 chars!)

Lets fix these and be clear about the constraints on the account name and be clearer about the possible errors. Or perhaps provide those contraints before the user starts putting in their info when  creating their account.

**Comment by quaiquai** [comment]
Is this when creating a username only? Is the user trying to create a username with the '@' symbol in the name?

**Comment by krs-world** [comment]
From my testing, if you create  a user name that is like krs@uncc.edu and then fill out the form, it fails with an error message. If I just use the name (without the @uncc.edu) then its fine, regardless of the size of the string (I went up over 30 letters) - the error message says less than 30, which is wrong and needs to be corrected.

**Comment by quaiquai** [comment]
I found the location of the issue. how long would you like the limit to the username to be?

**Comment by quaiquai** [comment]
make size range 3-40
