### ISSUE TITLE
cache issue..

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/bridgesAPI#74]
One of our users reports a cache related error:

_**When I connect to bridges to access data with _this code:_
Bridges bridges = new Bridges(3, "DebMDuke", "1043584906762");
DataSource ds = bridges.getDataSource();
****
I get this message
Error creating bridges cache directory

I'm able to see data, but I don't recall getting that error message.__** 

I have asked for more information (platform, etc).

**Comment by krs-world** [comment]
So she is using the Song data in her class assignment. From what I can tell, this doesnt use the cache, does it?

**Comment by esaule** [comment]
That's actually not a problem with bridgesAPI, but rather a client side issue
