### ISSUE TITLE
Scrolling enabled in assignment descriptions

### ISSUE THREAD

**Issue by kapooramanpreet** [BridgesUNCC/bridgesAPI#75]
I am not sure but I think the scroll css property needs to be turned off for overflows as the assignment description renders with scroll bars.

https://github.com/BridgesUNCC/bridgesAPI/blob/107498385dc1022fb0e9a1e57010c16fc081ff58/public/css/assignment.css#L143

![image](https://user-images.githubusercontent.com/29406643/170347295-662063ec-a044-49a3-94bd-e928f1a3a6b7.png)

**Comment by quaiquai** [comment]
done
