### ISSUE TITLE
sending a too big json should return a nice error

### ISSUE THREAD

**Issue by esaule** [BridgesUNCC/bridgesAPI#81]
if the json sent to the server is too big for mongo to store, the server returns a completely unhelpful error

See running assignment 44 without the population limit.

**Comment by esaule** [comment]
done in 08a55f9
Currently returning HTTP code 413 (Payload too large). 
checking whether that's the right code or not.

**Comment by esaule** [comment]
BTW, there is a client test that creates that error on purpose at:
bridges-client-testing/c++/web_tutorial_mastercopy/ls purposefully_breaking.cpp

**Comment by krs-world** [comment]
This might be just the limit of the post call itself,  and probably different from the DB limits?

**Comment by esaule** [comment]
the problem you were triggering was the DB limit.
The server should now (well, once we redeploy) send a nicer error message.

**Comment by esaule** [comment]
also clients should be checked for displaying a nice error message

**Comment by esaule** [comment]
This code craps out in Java 
```
import bridges.connect.Bridges;
import bridges.base.Array1D;
import bridges.base.Element;

public class Setup {
  public static void main(String[] args) throws Exception {

    /* Initialize a Bridges connection with your credentials */
    Bridges bridges = new Bridges(0, "BRIDGES_USER_ID", "BRIDGES_API_KEY");

    /* Set an assignment title */
    bridges.setTitle("Bridges Setup Introduction");
    bridges.setDescription("Visualize a simple Array with Bridges.");

    /* Set up the array dimensions, allocate an Array of Elements */
    int arraySize = 5*1000;
    Array1D<Integer> arr = new Array1D<Integer> (arraySize);

    String junk = "xxxxxxx";
    for (int i=0; i< 10; ++i)
	junk += junk;
    
    /* Populate the array with integers */
    for (int k = 0; k < arraySize; k++) {
      arr.getElement(k).setValue(k * k);
      arr.getElement(k).setLabel(String.valueOf(k * k)+junk);
    }

    /* Tell BRIDGES which data structure to visualize */
    bridges.setDataStructure(arr);

    /* Visualize the Array */
    bridges.visualize();
  }
}
```

with a fairly "bad" error message:

```There was a problem sending the visualization representation to the server. 
Server reported an error while serving request: The value of "offset" is out of range. It must be >= 0 && <= 17825792. Received 17825794```

**Comment by esaule** [comment]
It seems correct in c++, but not in java?

**Comment by esaule** [comment]
Just wrote purposefullybreaking in java and it seems to be reporting the error fine. What's happening with that other case?

**Comment by esaule** [comment]
It appears that there is a difference based on size. If we are just over the BSON size limit the api server generates the right error message. But it we are way overboard, it generates an other one. Writing purposefullybreaking2 to test the difference.

**Comment by esaule** [comment]
So if the JSON is about the right size but a bit too large, then the error is trapped by mongodb and propagated as a MongoServerError by mongoose. But if the JSON is way to big, then the serialization fails inside of mongoose. Unfortunately, this is not propagated to usercode wiht a  meaningful error message but a simple RangeError which could really be anything.

commit 9b378f25c757ad7351a8517efe6e19bee6dacd5a captures that RangeError when saving assignments and assume it is becasue the JSON is too big. This is a bit nasty, but can't do much better without appropriate support in mongoose
